language: ruby

services:
  - redis-server

env:
  - REDIS_URL='redis://localhost:6379'
    APP_NAME='travisci'

rvm:
  - 2.2.4
  - 2.3.1
  - ruby-head

install:
  - bundle install

script:
  - bundle exec rake
